### ISSUE TITLE
TypeError: cat() takes no keyword arguments

### ISSUE THREAD

**Issue by susht3** [jadore801120/attention-is-all-you-need-pytorch#10]
Traceback (most recent call last):                                              
  File "train.py", line 266, in <module>
    main()
  File "train.py", line 263, in main
    train(transformer, training_data, validation_data, crit, optimizer, opt)
  File "train.py", line 124, in train
    train_loss, train_accu = train_epoch(model, training_data, crit, optimizer)
  File "train.py", line 55, in train_epoch
    pred = model(src, tgt)
  File "/home/sushuting/local/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sushuting/workspace/attention-is-all-you-need-pytorch/transformer/Models.py", line 179, in forward
    enc_outputs, enc_slf_attns = self.encoder(src_seq, src_pos)
  File "/home/sushuting/local/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sushuting/workspace/attention-is-all-you-need-pytorch/transformer/Models.py", line 76, in forward
    enc_output, slf_attn_mask=enc_slf_attn_mask)
  File "/home/sushuting/local/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sushuting/workspace/attention-is-all-you-need-pytorch/transformer/Layers.py", line 18, in forward
    enc_input, enc_input, enc_input, attn_mask=slf_attn_mask)
  File "/home/sushuting/local/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sushuting/workspace/attention-is-all-you-need-pytorch/transformer/SubLayers.py", line 62, in forward
    outputs = torch.cat(torch.split(outputs, mb_size, dim=0), dim=-1) 
TypeError: cat() takes no keyword arguments

**Comment by pltrdy** [comment]
This issues has been fixed in pytorch, you should just upgrade it to get the fix

**Comment by jadore801120** [comment]
Hi @susht3,
The code is runnable with PyTorch 2.0.
Please take a look! Thank you!

Yu-Hsiang
