### ISSUE TITLE
RuntimeError: cublas runtime error

### ISSUE THREAD

**Issue by whxf** [jadore801120/attention-is-all-you-need-pytorch#113]
Train model with params:
```
Namespace(batch_size=64, cuda=True, d_inner_hid=2048, d_k=64, d_model=512, d_v=64, d_word_vec=512, data='data/weibo.tok.low.data', dropout=0.1, embs_share_weight=False, epoch=10, label_smoothing=True, log=None, max_seg_len=21, max_token_sequence_len=256, n_head=8, n_layers=6, n_warmup_steps=4000, no_cuda=False, proj_share_weight=True, save_mode='best', save_model='trained', src_vocab_size=64074, tgt_vocab_size=64074)
```

and I get error like:
```
Traceback (most recent call last):                         
  File "train.py", line 300, in <module>
    main()
  File "train.py", line 271, in main
    train(transformer, training_data, validation_data, optimizer, device, opt)
  File "train.py", line 154, in train
    model, training_data, optimizer, device, smoothing=opt.label_smoothing)
  File "train.py", line 75, in train_epoch
    pred = model(src_seq, src_pos, src_seg, tgt_seq, tgt_pos, tgt_seg)
  File "/home/LAB/lixi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/LAB/lixi/TopicSum/transformer/models.py", line 278, in forward
    enc_output, *_ = self.encoder(src_seq, src_pos, src_seg)
  File "/home/LAB/lixi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/LAB/lixi/TopicSum/transformer/models.py", line 155, in forward
    slf_attn_mask=slf_attn_mask)
  File "/home/LAB/lixi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/LAB/lixi/TopicSum/transformer/Layers.py", line 19, in forward
    enc_input, enc_input, enc_input, mask=slf_attn_mask)
  File "/home/LAB/lixi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/LAB/lixi/TopicSum/transformer/SubLayers.py", line 45, in forward
    q = self.w_qs(q).view(sz_b, len_q, n_head, d_k)
  File "/home/LAB/lixi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/LAB/lixi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 92, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/LAB/lixi/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1408, in linear
    output = input.matmul(weight.t())
RuntimeError: cublas runtime error : resource allocation failed at /pytorch/aten/src/THC/THCGeneral.cpp:228
srun: error: dell-gpu-01: task 0: Exited with exit code 1
```

How can I solve this?

**Comment by Crysitna** [comment]
same problem here when running the `translation.py`, with the same hardware during training

**Comment by whxf** [comment]
> same problem here when running the `translation.py`, with the same hardware during training

I have solved this problem. I found there are something in my own model structure. If you also change some parts of this model, you can try to check these part first.  In addition, it's more convenient to detect bug by running on cpu.

**Comment by Crysitna** [comment]
hi thanks for the update! running on cpu ready helps and my error is resulted from out-of-range index xd
