### ISSUE TITLE
RuntimeError: DataLoader worker (pid 26604) is killed by signal: Killed.

### ISSUE THREAD

**Issue by Ike-yang** [jadore801120/attention-is-all-you-need-pytorch#124]
The problem occurs when I run translate.py, has anyone got same issue?

python translate.py -model trained.chkpt -vocab data/multi30k.atok.low.pt -src data/multi30k/test.en.atok -no_cuda
[Info] Get 1000 instances from data/multi30k/test.en.atok
[Info] Trained model state loaded.
  - (Test):  85%|███████████████████████▉    | 29/34 [04:35<00:47,  9.52s/it]Traceback (most recent call last):
  File "translate.py", line 69, in <module>
    main()
  File "translate.py", line 61, in main
    all_hyp, all_scores = translator.translate_batch(*batch)
  File "/home/ike/Workspace/attention-is-all-you-need-pytorch/transformer/Translator.py", line 156, in translate_batch
Traceback (most recent call last):
  File "/home/ike/anaconda3/envs/seq2seq/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/home/ike/anaconda3/envs/seq2seq/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/ike/anaconda3/envs/seq2seq/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
    inst_dec_beams, len_dec_seq, src_seq, src_enc, inst_idx_to_position_map, n_bm)
  File "/home/ike/anaconda3/envs/seq2seq/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/home/ike/Workspace/attention-is-all-you-need-pytorch/transformer/Translator.py", line 116, in beam_decode_step
BrokenPipeError: [Errno 32] Broken pipe
    word_prob = predict_word(dec_seq, dec_pos, src_seq, enc_output, n_active_inst, n_bm)
  File "/home/ike/Workspace/attention-is-all-you-need-pytorch/transformer/Translator.py", line 96, in predict_word
    dec_output, *_ = self.model.decoder(dec_seq, dec_pos, src_seq, enc_output)
  File "/home/ike/anaconda3/envs/seq2seq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ike/Workspace/attention-is-all-you-need-pytorch/transformer/Models.py", line 146, in forward
    dec_enc_attn_mask=dec_enc_attn_mask)
  File "/home/ike/anaconda3/envs/seq2seq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ike/Workspace/attention-is-all-you-need-pytorch/transformer/Layers.py", line 46, in forward
    dec_output = self.pos_ffn(dec_output)
  File "/home/ike/anaconda3/envs/seq2seq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ike/Workspace/attention-is-all-you-need-pytorch/transformer/SubLayers.py", line 77, in forward
    output = self.w_2(F.relu(self.w_1(output)))
  File "/home/ike/anaconda3/envs/seq2seq/lib/python3.6/site-packages/torch/nn/functional.py", line 913, in relu
    result = torch.relu(input)
  File "/home/ike/anaconda3/envs/seq2seq/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 26604) is killed by signal: Killed.

**Comment by jiahuanluo** [comment]
OOM?

**Comment by jadore801120** [comment]
@Ike-yang 
It could be caused by CPU OOM.
Please try with the new code, which is more concise.
Hope it helps.
Thanks.
