### ISSUE TITLE
Error when training with -no_cuda

### ISSUE THREAD

**Issue by wz337** [jadore801120/attention-is-all-you-need-pytorch#126]
Hi, I am seeing an error when training with no cuda device. If anyone could help me with this, that would be great.

python train.py -data data/multi30k.atok.low.pt -save_model trained -save_mode best -proj_share_weight -label_smoothing --no_cuda

Namespace(batch_size=64, cuda=False, d_inner_hid=2048, d_k=64, d_model=512, d_v=64, d_word_vec=512, data='data/multi30k.atok.low.pt', dropout=0.1, embs_share_weight=False, epoch=10, label_smoothing=True, log=None, max_token_seq_len=52, n_head=8, n_layers=6, n_warmup_steps=4000, no_cuda=True, proj_share_weight=True, save_mode='best', save_model='trained', src_vocab_size=2911, tgt_vocab_size=3149)
[ Epoch 0 ]
Traceback (most recent call last):
  File "train.py", line 293, in <module>
    main()
  File "train.py", line 264, in main
    train(transformer, training_data, validation_data, optimizer, device ,opt)
  File "train.py", line 152, in train
    model, training_data, optimizer, device, smoothing=opt.label_smoothing)
  File "train.py", line 74, in train_epoch
    pred = model(src_seq, src_pos, tgt_seq, tgt_pos)
  File "/home/irisz/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/users/irisz/torchexplainer/transformer/Models.py", line 217, in forward
    dec_output, *_ = self.decoder(tgt_seq, tgt_pos, src_seq, enc_output,return_attns=self.return_attns)
  File "/home/irisz/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/users/irisz/torchexplainer/transformer/Models.py", line 147, in forward
    slf_attn_mask = (slf_attn_mask_keypad + slf_attn_mask_subseq).gt(0)
RuntimeError: expected device cpu and dtype Byte but got device cpu and dtype Bool

Thanks.

**Comment by jadore801120** [comment]
I guess it is the version issue.
In PyTorch v1.2.0, the `torch.bool` data type was introduced, while my data is tested under v1.1.0.
I haven't upgrade to the newest pytorch version because of CUDA driver issue.
I think it will be resolved with casting the `torch.bool` to `torch.byte` with `x.byte`.
Hope this helps
