### ISSUE TITLE
download dataset error

### ISSUE THREAD

**Issue by qimg412** [jadore801120/attention-is-all-you-need-pytorch#197]
hello, I want to download the WMT'17 by your codes,but I faid,could you tell me how to solve this problem,thank you so much.

the error as following:
Already downloaded and extracted http://data.statmt.org/wmt17/translation-task/training-parallel-nc-v12.tgz.
Already downloaded and extracted http://data.statmt.org/wmt17/translation-task/dev.tgz.
Downloading from http://storage.googleapis.com/tf-perf-public/official_transformer/test_data/newstest2014.tgz to newstest2014.tgz.
newstest2014.tgz: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "preprocess.py", line 336, in <module>
    main()
  File "preprocess.py", line 187, in main
    raw_test = get_raw_files(opt.raw_dir, _TEST_DATA_SOURCES)
  File "preprocess.py", line 100, in get_raw_files
    src_file, trg_file = download_and_extract(raw_dir, d["url"], d["src"], d["trg"])
  File "preprocess.py", line 71, in download_and_extract
    compressed_file = _download_file(download_dir, url)
  File "preprocess.py", line 93, in _download_file
    urllib.request.urlretrieve(url, filename=filename, reporthook=t.update_to)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by ylqi** [comment]
I have the same problem. The link won't open. Have you solved it?

**Comment by qimg412** [comment]
not yet, finally i solve this by download the dataset and try to make it in the paper's way

**Comment by warren-wzw** [comment]
> not yet, finally i solve this by download the dataset and try to make it in the paper's way

hello, i  met the same problem now ,have you solved this problem ?

**Comment by 97z** [comment]
I found this url is disabled.Maybe we can download this dataset by ourselves.But I dont try it yet.
