### ISSUE TITLE
ValueError: Cell is empty

### ISSUE THREAD

**Issue by Kznnd** [jadore801120/attention-is-all-you-need-pytorch#204]
when i run the commond in ubuntu
python preprocess.py -lang_src de -lang_trg en -share_vocab -save_data m30k_deen_shr.pkl
An error occurs as follows:
 ######
` (att) guest1@GPU2:~/zjl/attention-is-all-you-need-pytorch-master$ python preprocess.py -lang_src de -lang_trg en -share_vocab -save_data m30k_deen_shr.pkl
Namespace(data_src=None, data_trg=None, keep_case=False, lang_src='de', lang_trg='en', max_len=100, min_word_count=3, save_data='m30k_deen_shr.pkl', share_vocab=True)
[Info] Get source language vocabulary size: 5375
[Info] Get target language vocabulary size: 4556
[Info] Merging two vocabulary ...
[Info] Get merged vocabulary size: 9521
[Info] Dumping the processed data to pickle file m30k_deen_shr.pkl
Traceback (most recent call last):
  File "preprocess.py", line 337, in <module>
    main_wo_bpe()
  File "preprocess.py", line 332, in main_wo_bpe
    pickle.dump(data,f)
  File "/home/guest1/anaconda3/envs/att/lib/python3.6/site-packages/dill/_dill.py", line 267, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/home/guest1/anaconda3/envs/att/lib/python3.6/site-packages/dill/_dill.py", line 454, in dump
    StockPickler.dump(self, obj)
 
 ......

  File "/home/guest1/anaconda3/envs/att/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/guest1/anaconda3/envs/att/lib/python3.6/site-packages/dill/_dill.py", line 1177, in save_cell
    f = obj.cell_contents
ValueError: Cell is empty `
#####
How can I solve it?

**Comment by wangchuan** [comment]
same problem here

**Comment by Eric-dot** [comment]
same problem here!!
run in win10, How to solve it, I using the requirement environment 
dill==0.3.3
python==3.6.12
pytorch==1.2.0

**Comment by zhangsan5032** [comment]
都是伸手党啊

**Comment by haiyLiu** [comment]
I hava the same problem, refer to this issue[https://github.com/uqfoundation/dill/issues/383](url), it solved my problem!

**Comment by paulrich1234** [comment]
i just solved the problem by processing the data in the training process ,so i donot need to save the pickle file .
