### ISSUE TITLE
when I run the `python preprocess.py -lang_src de -lang_trg en -share_vocab -save_data m30k_deen_shr.pkl`.I have faced a problem 

### ISSUE THREAD

**Issue by HaitaoZhang-ZHT** [jadore801120/attention-is-all-you-need-pytorch#218]
when I run the `python preprocess.py -lang_src de -lang_trg en -share_vocab -save_data m30k_deen_shr.pkl`.I have face a problem ,which is`
Namespace(data_src=None, data_trg=None, keep_case=False, lang_src='de', lang_trg='en', max_len=100, min_word_count=3, save_data='m30k_deen_shr.pkl', share_vocab=True)
Traceback (most recent call last):
  File "preprocess.py", line 335, in <module>
    main_wo_bpe()
  File "preprocess.py", line 270, in main_wo_bpe
    src_lang_model = spacy.load(opt.lang_src)
  File "E:\app\aconda\envs\att\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "E:\app\aconda\envs\att\lib\site-packages\spacy\util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'de'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.`.
How can I solve it?

**Comment by WLSheng** [comment]
Run conda prompt as an administrator and download it:
python -m spacy download en
python -m spacy download de
