### ISSUE TITLE
Tensor data type error

### ISSUE THREAD

**Issue by ylmeng** [jadore801120/attention-is-all-you-need-pytorch#56]
This may have something to do with pytorch version (I use 0.4.0), but I think people should know:

`
Traceback (most recent call last):                                                                                                                   
  File "train.py", line 271, in <module>
    main()
  File "train.py", line 268, in main
    train(transformer, training_data, validation_data, crit, optimizer, opt)
  File "train.py", line 126, in train
    train_loss, train_accu = train_epoch(model, training_data, crit, optimizer)
  File "train.py", line 73, in train_epoch
    return total_loss/n_total_words, n_total_correct/n_total_words
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #2 'other'
`

**Comment by Xuwanjun9** [comment]
Try to change loss.data[0] to loss.item()

**Comment by jadore801120** [comment]
Hello @Xuwanjun9  Thanks for explanation!
Hello @ylmeng, sorry for that, it is a version issue. The code now has been updated to PyTorch 0.4.1, please take a look.
Thanks,
Yu-Hsiang
