### ISSUE TITLE
Pytorch Exception in Thread: ValueError: signal number 32 out of range

### ISSUE THREAD

**Issue by Finley1991** [jadore801120/attention-is-all-you-need-pytorch#78]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/wyf/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/wyf/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wyf/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 139, in _serve
    signal.pthread_sigmask(signal.SIG_BLOCK, range(1, signal.NSIG))
  File "/home/wyf/anaconda3/lib/python3.6/signal.py", line 60, in pthread_sigmask
    sigs_set = _signal.pthread_sigmask(how, mask)
ValueError: signal number 32 out of range

**Comment by expectopatronum** [comment]
I encountered the same error in a different project and resolved it by changing `num_workers = 4` to `num_workers = 0` while creating the `DataLoader`. (I am not sure for which system the code I am using was designed and maybe I am missing something to load data in parallel)
